# 开发环境
spring:
  datasource:
    url: jdbc:mysql://47.111.172.115:3306/egovalley_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: Ego!666
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 28830000
      maximum-pool-size: 9
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix:
      classpath: /templates
count:
  daily:
    path: E:\\output\\files\\daily.txt
  total:
    path: E:\\output\\files\\total.txt
total:
  count:
    time: 0 0 0 * * ?
ws:
  webSocketUrl: ws://127.0.0.1:10086
wss:
  webSocketUrl: wss://127.0.0.1:443
commonsDataPool:
  dequePoolSize: 200 # 队列大小
  threadInSize: 2 # 入线程数
  threadOutSize: 2 # 出线程数
  threadDataSize: 6 # 线程同时执行数
  inPoolLimitMillisecond: 3
init:
  thread:
    key1: value1
    key2: value2